

FROM node:18-alpine AS appbuild
ARG SOURCE_FOLDER="./"
WORKDIR /usr/src


RUN npm install -g pnpm@9
COPY ${SOURCE_FOLDER}pnpm-lock.yaml .
COPY ${SOURCE_FOLDER}pnpm-workspace.yaml .
COPY ${SOURCE_FOLDER}package.json .
COPY ${SOURCE_FOLDER}.npmrc .
COPY ${SOURCE_FOLDER} .
RUN pnpm install --frozen-lockfile
CMD pnpm nx run main-api:serve